### ISSUE TITLE
Error when trying to connect to the server

### ISSUE THREAD

**Issue by maximpris** [PolarbearDK/Miracle.FileZilla.Api#1]
FileZilla version 0.9.49

When I call the method Connect, I get an exception:

Exception Details: Miracle.FileZilla.Api.ProtocolException: Expected Byte 70 actual 50 at offset 0x0(0)

[ProtocolException: Expected Byte 70 actual 50 at offset 0x0(0)]
   Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, Byte expected) +59
   Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, Byte[] data) +35
   Miracle.FileZilla.Api.BinaryExtensions.Verify(BinaryReader reader, String s) +35
   Miracle.FileZilla.Api.<>c__DisplayClass8.<Connect>b__5(BinaryReader reader) +26
   Miracle.FileZilla.Api.FileZillaServerProtocol.Receive(Action`1 action) +144
   Miracle.FileZilla.Api.FileZillaServerProtocol.Connect(String password) +110

**Comment by PolarbearDK** [comment]
You get this exception when connecting to a port that host something other than a FileZilla server.
I admit the error is cryptic at best.

I have added a better exception message in version 2.0.3
