### ISSUE TITLE
Unable to read beyond the end of the stream when trying to connect

### ISSUE THREAD

**Issue by ghost** [PolarbearDK/Miracle.FileZilla.Api#10]
I'm trying to use this code outside of the server for the ftp site to connect. The same code while on the server works correctly. I have traced it to this method but not sure what is causing it. Any idea? 

public static void Verify(this BinaryReader reader, byte expected)
        {
            var actual = reader.ReadByte();
            if (actual != expected)
                throw ProtocolException.Create(reader, expected, actual);
        }

**Comment by PolarbearDK** [comment]
Have you enabled remote administration? 
Have you configured firewall?

I suggest that you install FileZilla Server on the "outside" machine and test if you can connect to your FTP server remotely usinge the admin interface (GUI).

**Comment by andrewschreiner** [comment]
Thanks, I was able to connect and all is working now.
