### ISSUE TITLE
Event based handling

### ISSUE THREAD

**Issue by acidos** [PolarbearDK/Miracle.FileZilla.Api#11]
First of all I would like to express my gratitude for this library. Keep this work up.

As far as I understand there is no event based handling. For example if I want to know that new connection arrived or client disconnected, I have to poll. FileZilla server interface is showing progress of everything nearly real-time. Do you plan to make some event based handling for your library?

**Comment by PolarbearDK** [comment]
I can assure you that FileZilla server interface is based on polling too.

Take a look at the sample Program.cs. The GetMessagesLoop() should be a good foundation for a "event" based approach. If you get it working, you are welcome to make a PR.
