### ISSUE TITLE
Exceptions in GetConnections

### ISSUE THREAD

**Issue by acidos** [PolarbearDK/Miracle.FileZilla.Api#12]
With FileZilla 0.9.57 I am getting exceptions in GetConnections:

**Unable to receive message: UserControl**
on other retry I am getting
**Multiple commands matched**
on 3rd retry success.

The exception happens when a new connection arrives.

**Comment by PolarbearDK** [comment]
I am unable to reproduce.
Plz elaborate?

**Comment by acidos** [comment]
This happens pretty stable on my environment.
I will try to make some isolated project which will reproduce it.

**Comment by PolarbearDK** [comment]
The error messages you are getting comes from a compromise i made in ReceiveMessage method. It tries to filter through all the messages that FileZilla server sends to get to the MessageType that you are looking for. It will try to find the desired message up to 5 times (hardcoded value). This value is apparently too low for your scenario.

There are 3 layers in the API:
- SocketCommunication: Handles raw communication with a socket 
- FileZillaServerProtocol: Adds the ability to send & receive FileZilla Server messages.
- FileZillaApi: A somewhat naive attempt to convert a multi threaded and out of order protocol into single threaded & in order.

For your scenario I would suggest that you drop using FileZillaApi and start using FileZillaServerProtocol. Just send commands, and handle all messages from ReceiveMessages() yourself. This will add complexity to your project, but you will gain a lot more control.

**Comment by PolarbearDK** [comment]
I have added a ReceiveMessageRetryCount property, and changed the default to 10.

**Comment by acidos** [comment]
Sorry, but it looks like there is a bug somewhere. No matter how large ReceiveMessageRetryCount is I am still getting those 2 exceptions, plus beyonnd end of stream exceptions occationally. All this happens when I query on existing socket connection multiple times(I have timer to query each second). The problem is solved only when I do it with open-query-close pattern, like in your examples. So I am pretty sure there is some protocol error.

**Comment by PolarbearDK** [comment]
You talked about an isolated project that reproduced the problem?

**Comment by acidos** [comment]
Not sure when I will be able to make it, but I'll try to make one and post here.
Briefly, it's just a loop of continuous GetConnections, then 2-3 connections come and go periodically.
