### ISSUE TITLE
Connect failing on closed connection

### ISSUE THREAD

**Issue by acidos** [PolarbearDK/Miracle.FileZilla.Api#13]
FileZillaApi ftp = new FileZillaApi(IPAddress.Loopback, 10101);

then somewhere in Task.Run

```
try
{
    if(!ftp.IsConnected)
    {
       ftp.Connect("12345");
    }

     List<Connection> connections = ftp.GetConnections();
     Console.WriteLine("{0} connections", connections.Count);
}
catch (Exception ee)
{
     Console.WriteLine(ee.Message);
}
```

First time when the code is running everything works ok, I'm getting the list.
Then I am killing active connection using TCPView, in order to simulate what happened in reality few times. The connection was killed by the FileZilla service. Now after killing I am getting 

> An existing connection was forcibly closed by the remote host

Next time I run, IsConnected is false and another exception happens on "ftp.Connect":

> Once the socket has been disconnected, you can only reconnect again asynchronously, and only to a different EndPoint.  BeginConnect must be called on a thread that won't exit until the operation has been completed.

I think Connect method should detect that the socket is invalid and create new one.

**Comment by PolarbearDK** [comment]
I think you need to redirect your question to Microsoft, as FileZillaApi is just a thin layer on top of System.Net.Sockets.Socket.

I dont have experience with long running FileZillaApi connections. I usually just do: 
- Connect
- Do stuff
- Disconnect (using a "Using block")

**Comment by acidos** [comment]
I don't think this question goes to MS. FileZilla probably have inactivity timeout, after which it will just close connection. So either keep-alive mechanism should be implemented or each operation like GetConnections or other should just do what you described - connect, do stuff, disconnect. If the case of remote connection close is not handled, I don't see much point exposing IsConnected.
