### ISSUE TITLE
Extension based pre-transfer rejection via transfer.cs

### ISSUE THREAD

**Issue by LindenCX** [PolarbearDK/Miracle.FileZilla.Api#14]
Hi Philip,

Would it be possible to use the transfer.cs on a loop to reject specific file extensions? I see that the following are defined in that class.

public string PhysicalFile { get; set; }
public string LogicalFile { get; set; }

Along with a connectionid, I assume if I could perform the loop on either of those and check the filename that I could reject specific file extensions. 

Thank you for your time.

**Comment by PolarbearDK** [comment]
You can check for unwanted file extensions that way but remember that what you are getting is a notification, not a "pre flight check".
All you can do with it is to kill the connection, which would be a bad user experience.
And if your program is too slow to react or FileZilla takes too long to notify your program then the file might get through anyway.

Hmmm... Come to think of it, You can upload with a different file extension, and rename the completed file.

I don't think it is possible.

**Comment by LindenCX** [comment]
Thanks for the quick response, yeah I thought of the renaming deal after posting this issue. We decided instead of limiting the extension we'll just check before anything is executed at the server level by CRC/SHA1.
