### ISSUE TITLE
Got this error while auth with fileZillaApi.Connect("123456");

### ISSUE THREAD

**Issue by corientdev** [PolarbearDK/Miracle.FileZilla.Api#15]
Unsupported FileZilla protocol version:0.1.40.0 server version:0.9.59.0 (API version: 3.0.3.0). Please report issue at https://github.com/PolarbearDK/Miracle.FileZilla.Api.

**Comment by PolarbearDK** [comment]
Looking at it now.  
Until a fix is available, use 0.9.57 or earlier

**Comment by PolarbearDK** [comment]
New version available that fixes support for 0.9.58+

**Comment by corientdev** [comment]
Really appreciate you for amazing response timing and fix. You rock.
Thanks for amazing library.
I have one question in mind. How library interact with filezilla server. I mean it manupulate the UI programatically or filezilla server is made to  takes command for everything like create user and everything and then reload setting by itself. How it works?
On Oct 8, 2016 1:39 AM, Philip Hoppe notifications@github.com wrote:New version available that fixes support for 0.9.58+

**Comment by PolarbearDK** [comment]
The "UI" communicates with the server over TCP/IP.  That's what the "127.0.0.1" port 14147 is for.
I have just reverse engineered that communication. It's binary and really hard to read.

**Comment by corientdev** [comment]
What is the need of reverse engineering? I mean they have provided the source code openly accessible toeveryone i guess. Just out of curiosity i am asking
On Oct 9, 2016 7:30 PM, Philip Hoppe notifications@github.com wrote:The "UI" communicates with the server over TCP/IP.  That's what the "127.0.0.1" port 14147 is for.
I have just reverse engineered that communication. It's binary and really hard to read.

**Comment by PolarbearDK** [comment]
If you have a specification for a protocol, you can implement it, but in this case no specification were available. 

I guess you could deduce the protocol from the FileZilla server source code, but it:
- contains almost no comments except for headers
- uses non descriptive variable names.
- is not very well structured, and violates most rules for good software. But it sure is fast :)

What I did was look at the hex-dump of the messages going to and from the server, and then used the source code as a guide to figure out what was going on. You may call it "reverse engineering", "reimplementation" ect.
