### ISSUE TITLE
User ForceSsl misses the undetermined option

### ISSUE THREAD

**Issue by CraftLord** [PolarbearDK/Miracle.FileZilla.Api#17]
The User.ForceSsl property can have the next values:
0	False
1	True
2	Undetermined

When you use GetAccountSettings, all the Undetermined values are set to True.
When you add a new User to the accountSettins and do fileZillaApi.SetAccountSettings(accountSettings)
All the Users wich had set ForceSsl to Undetermined will be changed to ForceSsl set to True.

**Comment by PolarbearDK** [comment]
Fixed in version 3.2.0.
