### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by MarioX1** [PolarbearDK/Miracle.FileZilla.Api#2]
Its not a bug, but no idea where to post 'many thanks'.
Very usefull API!

We setup a intranet website where use can per one-click create random ftp access. account and files are automatically deleted after specified time.

Little bit tricky was it, to get it running under Win2003.
FileZilla stops support with 0.9.43

Mario.

**Comment by PolarbearDK** [comment]
You are welcome.
I have now verified that API works with 0.9.43 server, and released a new NuGet package that supports 0.9.43-0.9.52+
