### ISSUE TITLE
Trying to set an directory-alias: BC30311: Value of type 'String' cannot be converted to 'List(Of String)'.

### ISSUE THREAD

**Issue by tomtheone** [PolarbearDK/Miracle.FileZilla.Api#22]
Hi all

I've a vb.net project and i would like to use the API. Do you have an idea why this code sample throws this error?

![Microsoft Visual Studio](https://user-images.githubusercontent.com/12658451/68044831-6b9b8300-fcd8-11e9-8f95-3116e0c97a72.png)

Error: BC30311: Value of type 'String' cannot be converted to 'List(Of String)'.

Any ideas what i'm doing wrong?

I would like to create a config like this:

![usr](https://user-images.githubusercontent.com/12658451/68045932-f4b3b980-fcda-11e9-82a4-e42719178cd7.png)

Best regards
Tom

**Comment by tomtheone** [comment]
Hi all

I had to add this to my .vb file:

```
Friend Class ArrayList(Of T)
    Inherits List(Of String)
End Class
```

Afterwards this was working:

```
    Sub AddUser()

        Dim lstDirectoryAliases As List(Of String) = New ArrayList(Of String)()
        lstDirectoryAliases.Add("/pub_html")

        Using fileZillaApi As IFileZillaApi = New FileZillaApi(IPAddress.Parse(strServerAddr), strServerPort)
            fileZillaApi.Connect(strServerPass)
            Dim accountSettings = fileZillaApi.GetAccountSettings()
            ' Reference to existing group
            Dim user = New User()
            user.GroupName = strGroupName
            user.UserName = strUserName
            user.ForceSsl = TriState.No
            user.BypassUserLimit = TriState.No
            user.SharedFolders = New List(Of SharedFolder)() From {
                New SharedFolder() With {
                    .Directory = strUserDir,
                    .AccessRights = AccessRights.DirList Or AccessRights.DirSubdirs Or AccessRights.DirCreate Or AccessRights.DirDelete Or
                                    AccessRights.FileRead Or AccessRights.FileWrite Or AccessRights.FileDelete Or AccessRights.FileAppend,
                    .Aliases = lstDirectoryAliases
                    }
                }
            user.AssignPassword(strUserPass, fileZillaApi.ProtocolVersion)
            accountSettings.Users.Add(user)
            fileZillaApi.SetAccountSettings(accountSettings)
        End Using
    End Sub
```
I wish everybody a good start into the new week.

Best regards
Tom

**Comment by PolarbearDK** [comment]
if you look in [SharedFolder.cs](https://github.com/PolarbearDK/Miracle.FileZilla.Api/blob/master/Source/Miracle.FileZilla.Api/SharedFolder.cs) you can see that Aliases (as the plural name indicates) is a list of string.

You can do Aliases.Add("Foo") 

I have no idea if this requires special syntax in VB.
