### ISSUE TITLE
How to modify/remove a user with Miracle.FileZilla.Api?

### ISSUE THREAD

**Issue by tomtheone** [PolarbearDK/Miracle.FileZilla.Api#23]
Hi all

I'm having problems understanding the referenced documentation from here.

https://github.com/PolarbearDK/Miracle.FileZilla.Api/issues/19

The doc says:

> 4: Modify Users and Groups lists as desired (add/change/delete).
> accountSettings.Users.Add(user);

It seems those options are invalid:

accountSettings.Users.Delete(user)
accountSettings.Users.Change(user)

It seems this option is valid, but does not remove a user:

accountSettings.Users.Remove(user)

Are there some code samples for example how to reset a password for and/or how to delete a user?

Best regards
Tom

**Comment by tomtheone** [comment]
Hi all

Removing a user is solved.

```
        Dim strUserName As String = "MyTestUser"


        Using fileZillaApi As IFileZillaApi = New FileZillaApi(IPAddress.Parse(strServerAddr), strServerPort)
            fileZillaApi.Connect(strServerPass)
            Dim accountSettings = fileZillaApi.GetAccountSettings()
            ' Reference to existing group
            Dim user = New User()
            user.UserName = strUserName
            accountSettings.Users.RemoveAll(Function(x) x.UserName = strUserName)
            fileZillaApi.SetAccountSettings(accountSettings)
        End Using
```

I found the C# example [here ](https://csharp.hotexamples.com/examples/-/FileZillaApi/SetAccountSettings/php-filezillaapi-setaccountsettings-method-examples.html) and was able use the information in my .NET project.

Best regards
Tom

**Comment by PolarbearDK** [comment]
Hi,

Glad you found the solution yourself.

Note! There are examples of how to use most of the API in the [sample application](https://github.com/PolarbearDK/Miracle.FileZilla.Api/blob/master/Source/Miracle.FileZilla.Api.Samples/Program.cs).

**Comment by tomtheone** [comment]
Hi Philip

Thank you, this helped a lot, here is my .net sample.

```
        Using fileZillaApi As IFileZillaApi = New FileZillaApi(IPAddress.Parse(strServerAddr), strServerPort)

            fileZillaApi.Connect(strServerPass)
            Dim accountSettings = fileZillaApi.GetAccountSettings()

            Dim user = accountSettings.Users.FirstOrDefault(Function(x) x.UserName = strUserName)

            If user Is Nothing Then
                Console.WriteLine("ERROR | User " & strUserName & " not found.")
            Else
                ' Modify password of the user
                user.AssignPassword(strUserPass, fileZillaApi.ProtocolVersion)
                fileZillaApi.SetAccountSettings(accountSettings)
            End If

        End Using
```

Thank you again. Good week,
Br
Tom
