### ISSUE TITLE
[Question] - Can I set the SALT and PASSWORD hash?

### ISSUE THREAD

**Issue by joshgo** [PolarbearDK/Miracle.FileZilla.Api#24]
Hi, 

I was looking at the README (example 4), and saw that the **Password** can be assigned. However, I think that's not the case anymore at least with the latest version or even longer. Anyway, I want to be able to assign the Password (hash) and Salt directly. It's computed in another system and the hash/salt is used in various systems to authtenticate the user. Now, I want to use the same hash/salt to create a user for FileZilla, so the user can use their existing credential.

Anyway, would it ever be possible to make the Password and Salt property assignable? Are there pitfalls with having these 2 properties available to set?

(Note: I tested our hash/salt manually by setting it in the FileZilla-server.xml file, and it worked perfectly)

**Comment by PolarbearDK** [comment]
Why do you need to set the salt? It is there to make passwords harder to crack, and has nothing to do with the credentials (username/password). I might be wrong but i think you are doing something wrong here.

However if you really need this, you can add an overload to AssignPassword like this:
```csharp
public void AssignPassword(string password, string salt, int protocolVersion)
{
    if (protocolVersion < ProtocolVersions.Sha512)
    {
        throw new ProtocolException("Salt not supported in this version.");
    }
    else
    {
        if(salt.Length != SaltSize)
        {
            throw new ProtocolException("Wrong salt size.");
        }

        Salt = salt;
        Password = HashPasswordSha512(password, Salt);
    }
}
```

Note! You also need to check that provided salt only contains characters form the list of valid characters.

**Comment by PolarbearDK** [comment]
Are you satisfied with the solution to this? Can I close this issue?
