### ISSUE TITLE
How to change password and other settings without removing/adding a user?

### ISSUE THREAD

**Issue by tomtheone** [PolarbearDK/Miracle.FileZilla.Api#25]
Is it possible to change a password (and other general settings of a user/group) without the need to delete and re-add the user by using the Mirable.FileZilla.Api?

**Comment by PolarbearDK** [comment]
Yes.
Just find the specific user in the accountSettings.Users list and change whatever you like to change.

**Comment by tomtheone** [comment]
Hi PolarbearDK

Thanks for your reply.

I guess i have to use  accountSettings.Users.Find somehow. I'm not geting it and i can not find an example. Could you help out a little bit? Would be awesome.

**Comment by PolarbearDK** [comment]
I have added an example for you.
See ChangeExistingUser() method in sample [Program.cs](https://github.com/PolarbearDK/Miracle.FileZilla.Api/blob/master/Source/Miracle.FileZilla.Api.Samples/Program.cs)
