### ISSUE TITLE
[Question] Is it maintained and updated to work with latest FZ server versions?

### ISSUE THREAD

**Issue by roboirc** [PolarbearDK/Miracle.FileZilla.Api#27]

**Comment by PolarbearDK** [comment]
Is it maintained?: Yes
Is it updated to work with latest FZ server versions? Yes

This information is available on [main project page](https://github.com/PolarbearDK/Miracle.FileZilla.Api).

There has been [no new server versions](https://filezilla-project.org/versions.php?type=server) for several years, and that is the reason for lack of updates.
