### ISSUE TITLE
How to put several directory to the user?

### ISSUE THREAD

**Issue by herledant** [PolarbearDK/Miracle.FileZilla.Api#28]
Hello,
I appreciate a lot your work.
Anyway could you provide the way we can put several directory to the same user?

Regard's

**Comment by PolarbearDK** [comment]
You add all the folders to SharedFolders property.

**Comment by herledant** [comment]
Hello,
Sorry but Could you provide an example Please ?

Le dim. 5 avr. 2020 à 21:09, Philip Hoppe <notifications@github.com> a
écrit :

**Comment by PolarbearDK** [comment]
You find examples of most usage in the "Samples" application.
https://github.com/PolarbearDK/Miracle.FileZilla.Api/blob/3b6cb49efa5f123819f3a256827b3d7dcce83167/Source/Miracle.FileZilla.Api.Samples/Program.cs#L246-L258

**Comment by herledant** [comment]
Thanks a lot !

Le dim. 5 avr. 2020 à 21:44, Philip Hoppe <notifications@github.com> a
écrit :
