### ISSUE TITLE
why no create dic method

### ISSUE THREAD

**Issue by buringhe** [PolarbearDK/Miracle.FileZilla.Api#29]
![1608197757(1)](https://user-images.githubusercontent.com/7788618/102469952-57f2dd80-408e-11eb-9004-e456a82a150b.png)
when I  dynamic create user ,first I need  create directory,second I will to set user info ,and add user,please help me how to create directory

**Comment by PolarbearDK** [comment]
The FileZilla Server API doesn't support that. 
However if you run this on the same server as the FileZilla Server then you can just use:
https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.createdirectory
