### ISSUE TITLE
[2.1.0.0] NullReferenceException in SendCommand method

### ISSUE THREAD

**Issue by LordBenjamin** [PolarbearDK/Miracle.FileZilla.Api#3]
SendCommand(MessageType messageType, Action<BinaryWriter> dataAction) throws an NRE when using the FileZillaApi class as the Log property is not initialized.

I worked around this by wrapping the log line in a null check:
            if (Log != null) {
                Log.WriteLine("Send: {0}", messageType);
            }

**Comment by PolarbearDK** [comment]
Fixed in 2.1.1.0

**Comment by LordBenjamin** [comment]
Updated to 2.1.1.0 - thanks!
