### ISSUE TITLE
How to add allowed and dissalowed ip

### ISSUE THREAD

**Issue by madsholme** [PolarbearDK/Miracle.FileZilla.Api#30]
How do you add this?

i can see i need to create a list, but when i do 

                var accountSettings = fileZillaApi.GetAccountSettings();
                var user = new User
                {
                    //GroupName = ExampleGroupName, // Reference to group
                    UserName = ftpuser,
               
                    DisallowedIPs = new List<DisallowedIPs>()
                    {
                       new DisallowedIPs()
                        {

                        }
                    
                    }

it just says the type or namespace DisallowedIPs could not be found. ?

**Comment by madsholme** [comment]
List<string> ipdisallow = new List<string>();
                ipdisallow.Add("*");

                List<string> ipallow = new List<string>();
                ipallow.Add("7.7.7.7");
                ipallow.Add("8.8.8.8");

**Comment by PolarbearDK** [comment]
FYI: AllowedIPs/DisallowedIPs properties are lists and allows you to do:
```CSHARP
user.DisallowedIPs.Add("*");
user.AllowedIPs.Add("7.7.7.7");
user.AllowedIPs.Add("8.8.8.8");
```
