### ISSUE TITLE
The problem of xamarin

### ISSUE THREAD

**Issue by qinjianzhanqing** [PolarbearDK/Miracle.FileZilla.Api#31]
![image](https://user-images.githubusercontent.com/20415253/121358724-6814b700-c965-11eb-911a-c89085a4257d.png)

**Comment by PolarbearDK** [comment]
This indicates that there is a service running at the port you are connecting to, but you are actively blocked from connecting.
Check IP address, port and firewall. 
Can you connect using FileZillaServer GUI?

**Comment by PolarbearDK** [comment]
I guess you figured it out... Closing.
