### ISSUE TITLE
Real time TransferInfo?

### ISSUE THREAD

**Issue by Almis90** [PolarbearDK/Miracle.FileZilla.Api#5]
Sometimes I see the TransferInfo and sometimes not, I not sure what wrong... Can you help me please?

https://gist.github.com/Almis90/851e0131c42064661cec

**Comment by Almis90** [comment]
After some more testing I found that the first 1-3 downloads don't have TransferInfo (bytes count) but the next one has, then again the first 1-3 don't have and then next one has. Can you please look at it? Thank you.

**Comment by PolarbearDK** [comment]
Upon a file transfer you seem to get:
- a start transfer "UserControl (Transfer)"
- an end transfer "UserControl (Transfer)"

In between you MIGHT get one or more "Transfer (TransferInfo)" messages but only if the transfer takes some time. You can definitely not count on it.

You can check it using the sample test programs GetMessagesLoop() function.

**Comment by Almis90** [comment]
It's also seems that I had this problem cause the file transfer was very fast, after setting limit I was able to see the transfer. I don't mind to lose a few transfers info. Thank you.
