### ISSUE TITLE
Is it possible to find to which connection/ip a transfer info belongs?

### ISSUE THREAD

**Issue by Almis90** [PolarbearDK/Miracle.FileZilla.Api#6]
I receiving the TransferInfo but the only information it has is Type and Count. Is there any way to find to which connection or ip it belongs?

**Comment by PolarbearDK** [comment]
I don't know. 
I suggest you ask on the filezilla server forum on https://forum.filezilla-project.org/viewforum.php?f=6

**Comment by Almis90** [comment]
Registered yesterday and still no verification email.. I will contact them directly to see the issue with registering.

**Comment by PolarbearDK** [comment]
Not really a problem with Miracle.FileZilla.Api.
I'm going to close this.
