### ISSUE TITLE
Got Exception: Unsupported FileZilla protocol version:0.1.30.0.

### ISSUE THREAD

**Issue by aleh4d** [PolarbearDK/Miracle.FileZilla.Api#7]
Exception: "Unsupported FileZilla protocol version:0.1.30.0."

**Comment by PolarbearDK** [comment]
I'm on it, but it will take some time. 

Downgrade your FileZilla Server to 0.9.53 until a fix is available.

**Comment by StephenJabs** [comment]
I had to downgrade all the way to 0.9.48.  Admittedly, I did not try 0.9.49 or 0.9.50 (had to get my application back up and running, so I went to last known good release), but all the other versions in between threw an exception "Unsupported FileZilla protocol version:0.1.20.0".

**Comment by mrrcomp** [comment]
Its working for me on 9.53 :) on two different VPS servers :)

Meir

**Comment by PolarbearDK** [comment]
New version 3.0.0 released supporting 0.9.54/55.
Breaking change: Passwords need to be assigned using AssignPassword method.

Note that there are is a problem with 50.000+ users in latest version of server:
https://forum.filezilla-project.org/viewtopic.php?f=6&t=39949

Just testet from .46 up to .55 and they all work except .51 which was a lemon.
@StephenJabs which NuGet package version are you using?!?

**Comment by StephenJabs** [comment]
I was using NuGet package 2.1.2 but couldn’t get it to work with 0.9.53.  I’ve started the switch to v3.0.0 and will upgrade the server to 0.9.55 when able.
