### ISSUE TITLE
Write Permission  on User Create

### ISSUE THREAD

**Issue by mrrcomp** [PolarbearDK/Miracle.FileZilla.Api#8]
Hi

Firstly koodos on the code. I just finished integrating it into a website of mine however i really need to give the created user "Write Permissiions" oh him home directory.

Is this possible?

Regards

Meir

**Comment by PolarbearDK** [comment]
You do it using **AccessRights.FileWrite**:

``` csharp
var newUser = new User
{
    GroupName = GroupName,
    UserName = UserName,
    Password = User.HashPassword("..."),
    SharedFolders = new List<SharedFolder>()
    {
        new SharedFolder()
        {
            Directory = @"C:\Hello\World",
            AccessRights = AccessRights.DirList | AccessRights.DirSubdirs | AccessRights.FileRead |
                    AccessRights.IsHome | AccessRights.FileWrite
        }
    }
};
```

**Comment by mrrcomp** [comment]
Thanks :)

Keep up the good work... 

Meir

**Comment by mrrcomp** [comment]
Hi

Thanks this works great however after creating the user  any attempts at logging in says the account is disabled . If I go to the Server I see the account as enabled I must disable and enable and then the user can connect ???

Suggestions?

Meir

**Comment by PolarbearDK** [comment]
Well, yes. I can see how this can be confusing. 

Let me explain.
For a user to be enabled it must have:
- Enabled=Yes
- Enabled=Default, and have a group membership with Enabled=Yes (Default=inherit from group).

Users default to Enabled=Default, and if you do not assign a GroupName, it will not be enabled.

I'm adding a fix for that.

**Comment by mrrcomp** [comment]
Hi,
Thanks for all your help.  Was wondering if I can impose on you for code snippet to change a users pwd.

Thanks..

Meir

Sent from my android by Outlookhttp://taps.io/outlookmobile Mobile

On Wed, Feb 10, 2016 at 10:35 AM -0800, "Philip Hoppe" <notifications@github.com<mailto:notifications@github.com>> wrote:

You do it using AccessRights.FileWrite:

var newUser = new User
{
    GroupName = GroupName,
    UserName = UserName,
    Password = User.HashPassword("..."),
    SharedFolders = new List<SharedFolder>()
    {
        new SharedFolder()
        {
            Directory = @"C:\Hello\World",
            AccessRights = AccessRights.DirList | AccessRights.DirSubdirs | AccessRights.FileRead |
                    AccessRights.IsHome | AccessRights.FileWrite
        }
    }
};

##

**Comment by PolarbearDK** [comment]
From version 3.0.0 forward, this is done using: 
user.AssignPassword("newpassword", fileZillaApi.ProtocolVersion);

**Comment by mrrcomp** [comment]
Thanks.. how do I get the “proper user” from the server?

Meir

**Comment by PolarbearDK** [comment]
``` csharp
var accountSettings = fileZillaApi.GetAccountSettings();
var user = accountSettings.Users.Single(x => x.UserName == userName);
user.AssignPassword("newpassword", fileZillaApi.ProtocolVersion);
fileZillaApi.SetAccountSettings(accountSettings);
```

**Comment by mrrcomp** [comment]
You’re a life saver ☺

Meir
